/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication20;

import java.awt.CardLayout;
/**
 *
 * @author osman
 */
public class MiPanel extends javax.swing.JFrame {

    private PanelPrincipal panelPrincipal;
    private PanelBasico panelBasico;
    private PanelUnir panelUnir;
    private PanelConc panelConc;
    private PanelConv panelConv;
    private PanelAn panelAn;
    private PanelCK panelCK;
    private PanelCPos panelCPos;
    private PanelOpc panelOpc;
    private PanelUAL panelUAL;
    private PanelCalc panelCalc;
    private CardLayout cardLayout;
    public AFN elGranAFN;
    public AFD elAFDfinal;
    
    /**
     * Creates new form MiPanel
     */
    public MiPanel() {
            initComponents();

        // Configura y aplica el CardLayout en un solo lugar
        cardLayout = new CardLayout();
        PanelContenedor.setLayout(cardLayout);

        // Llama al método que añade los paneles
        configurarCardLayout(); // Renombré el método para mayor claridad
     
    }

    private void configurarCardLayout() {
        // Obtenemos el layout del panel que configuramos en el diseñador
        // NOTA: NetBeans podría no haber creado la variable panelContenedor aún.
        // Si da error, asegúrate de haberle cambiado el nombre en el paso 2.
        // Si sigue sin funcionar, créalo tú mismo:
        // panelContenedor = new javax.swing.JPanel();


        // Creamos una instancia de cada panel-pantalla
        panelPrincipal = new PanelPrincipal();
        panelBasico = new PanelBasico();
        panelUnir = new PanelUnir();
        panelConc = new PanelConc();
        panelConv = new PanelConv();
        panelAn = new PanelAn();
        panelCK = new PanelCK();
        panelCPos = new PanelCPos();
        panelOpc = new PanelOpc();
        panelUAL = new PanelUAL();
        panelCalc = new PanelCalc();


        // Los añadimos al panel contenedor, cada uno con un nombre único
        PanelContenedor.add(panelPrincipal, "Principal");
        PanelContenedor.add(panelBasico, "BASICO");
        PanelContenedor.add(panelUnir, "UNIR");
        PanelContenedor.add(panelConc, "CONC");
        PanelContenedor.add(panelConv, "CONV");
        PanelContenedor.add(panelAn, "AN");
        PanelContenedor.add(panelCK, "CK");
        PanelContenedor.add(panelCPos, "CPOS");
        PanelContenedor.add(panelOpc, "OPC");
        PanelContenedor.add(panelUAL, "UAL");
        PanelContenedor.add(panelCalc, "CALC");

        // Opcional: Mostramos el panel básico por defecto
        cardLayout.show(PanelContenedor, "Principal");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemBasico = new javax.swing.JMenuItem();
        itemUnir = new javax.swing.JMenuItem();
        itemConc = new javax.swing.JMenuItem();
        itemCPos = new javax.swing.JMenuItem();
        itemCK = new javax.swing.JMenuItem();
        itemOpc = new javax.swing.JMenuItem();
        itemUAL = new javax.swing.JMenuItem();
        itemConv = new javax.swing.JMenuItem();
        itemProb = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelContenedor.setPreferredSize(new java.awt.Dimension(600, 500));

        javax.swing.GroupLayout PanelContenedorLayout = new javax.swing.GroupLayout(PanelContenedor);
        PanelContenedor.setLayout(PanelContenedorLayout);
        PanelContenedorLayout.setHorizontalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        PanelContenedorLayout.setVerticalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N

        jMenu1.setText("AFN's");
        jMenu1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N

        itemBasico.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        itemBasico.setText("Basico");
        itemBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBasicoActionPerformed(evt);
            }
        });
        jMenu1.add(itemBasico);

        itemUnir.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        itemUnir.setText("Unir");
        itemUnir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUnirActionPerformed(evt);
            }
        });
        jMenu1.add(itemUnir);

        itemConc.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        itemConc.setText("Concatenar");
        itemConc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConcActionPerformed(evt);
            }
        });
        jMenu1.add(itemConc);

        itemCPos.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        itemCPos.setText("C+");
        itemCPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCPosActionPerformed(evt);
            }
        });
        jMenu1.add(itemCPos);

        itemCK.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        itemCK.setText("C*");
        itemCK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCKActionPerformed(evt);
            }
        });
        jMenu1.add(itemCK);

        itemOpc.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        itemOpc.setText("Opcional");
        itemOpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOpcActionPerformed(evt);
            }
        });
        jMenu1.add(itemOpc);

        itemUAL.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        itemUAL.setText("Union para analizador lexico");
        itemUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUALActionPerformed(evt);
            }
        });
        jMenu1.add(itemUAL);

        itemConv.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        itemConv.setText("AFN -> AFD");
        itemConv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConvActionPerformed(evt);
            }
        });
        jMenu1.add(itemConv);

        itemProb.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        itemProb.setText("Probar analizador lexico");
        itemProb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProbActionPerformed(evt);
            }
        });
        jMenu1.add(itemProb);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Analizador sintactico");
        jMenu2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N

        jMenu3.setText("Descenso recursivo");

        jMenuItem4.setText("Calculadora");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBasicoActionPerformed
        cardLayout.show(PanelContenedor, "BASICO");
    }//GEN-LAST:event_itemBasicoActionPerformed

    private void itemUnirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUnirActionPerformed
        // 1. Le pedimos al panel "Unir" que actualice sus datos
        panelUnir.inicializarComboBoxes();
        // 2. Ahora que está actualizado, lo mostramos
        cardLayout.show(PanelContenedor, "UNIR");
    }//GEN-LAST:event_itemUnirActionPerformed

    private void itemConcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConcActionPerformed
        panelConc.inicializarComboBoxes();
        
        cardLayout.show(PanelContenedor, "CONC");
    }//GEN-LAST:event_itemConcActionPerformed

    private void itemCPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCPosActionPerformed
        panelCPos.inicializarComboBoxes();
        
        cardLayout.show(PanelContenedor, "CPOS");
    }//GEN-LAST:event_itemCPosActionPerformed

    private void itemCKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCKActionPerformed
        panelCK.inicializarComboBoxes();
        
        cardLayout.show(PanelContenedor, "CK");
    }//GEN-LAST:event_itemCKActionPerformed

    private void itemOpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOpcActionPerformed
        panelOpc.inicializarComboBoxes();
        
        cardLayout.show(PanelContenedor, "OPC");
    }//GEN-LAST:event_itemOpcActionPerformed

    private void itemUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUALActionPerformed
        panelUAL.actualizarTabla();
        
        cardLayout.show(PanelContenedor, "UAL");
    }//GEN-LAST:event_itemUALActionPerformed

    private void itemConvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConvActionPerformed
        cardLayout.show(PanelContenedor, "CONV");
    }//GEN-LAST:event_itemConvActionPerformed

    private void itemProbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProbActionPerformed
        cardLayout.show(PanelContenedor, "AN");
    }//GEN-LAST:event_itemProbActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        cardLayout.show(PanelContenedor, "CALC");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JMenuItem itemBasico;
    private javax.swing.JMenuItem itemCK;
    private javax.swing.JMenuItem itemCPos;
    private javax.swing.JMenuItem itemConc;
    private javax.swing.JMenuItem itemConv;
    private javax.swing.JMenuItem itemOpc;
    private javax.swing.JMenuItem itemProb;
    private javax.swing.JMenuItem itemUAL;
    private javax.swing.JMenuItem itemUnir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
