/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication20;

/**
 *
 * @author osman
 */
public class PanelAn extends javax.swing.JPanel {
    
    private javax.swing.table.DefaultTableModel tableModel;
    private String rutaArchivoAFD; // Para guardar la ruta del archivo AFD
    
    public PanelAn() {
        initComponents();
        
        // Configurar el modelo para la tabla de resultados
        tableModel = new javax.swing.table.DefaultTableModel(
            new Object[]{"Token", "Lexema"}, // Nombres de las columnas
            0 // Empezar con 0 filas
        );

        // Asignar el modelo a nuestra tabla
        tblResultados.setModel(tableModel);
        java.awt.Font sansSerifFont = new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12);
    
        tblResultados.setDefaultRenderer(Object.class, new ErrorRowRenderer());
        
        // Aplicar fuente a las celdas de la tabla
        tblResultados.setFont(sansSerifFont);
    
        //Aplicar la fuente al encabezado de la tabla (opcional, pero recomendado)
        tblResultados.getTableHeader().setFont(sansSerifFont.deriveFont(java.awt.Font.BOLD, 13f));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSigma = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRutaArchivo = new javax.swing.JTextField();
        btnCargarArchivo = new javax.swing.JButton();
        btnAnalizar = new javax.swing.JButton();
        scrollPaneTabla = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("Sigma:");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("ArchivoAFD:");

        txtRutaArchivo.setEditable(false);

        btnCargarArchivo.setBackground(new java.awt.Color(102, 153, 255));
        btnCargarArchivo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCargarArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnCargarArchivo.setText("Cargar...");
        btnCargarArchivo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoActionPerformed(evt);
            }
        });

        btnAnalizar.setBackground(new java.awt.Color(102, 153, 255));
        btnAnalizar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAnalizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAnalizar.setText("AnalizarCadena");
        btnAnalizar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneTabla.setViewportView(tblResultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSigma)))
                    .addComponent(btnAnalizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPaneTabla, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtSigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtRutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(scrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Seleccionar archivo de AFD (.txt)");

        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = fileChooser.getSelectedFile();
            this.rutaArchivoAFD = archivo.getAbsolutePath(); // Guardamos la ruta en la variable de instancia
            txtRutaArchivo.setText(this.rutaArchivoAFD); // Mostramos la ruta en el TextField
        }
    }//GEN-LAST:event_btnCargarArchivoActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        // --- 1. Obtener las entradas del usuario y validar ---
        String cadena = txtSigma.getText();

        if (cadena.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingresa una cadena para analizar.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (this.rutaArchivoAFD == null || this.rutaArchivoAFD.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, carga un archivo de definición de AFD.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // --- 2. Limpiar la tabla de resultados anteriores ---
        tableModel.setRowCount(0);

        // --- 3. Crear el analizador y procesar la cadena ---
        try {
            analizadorLexico analizador = new analizadorLexico(cadena, this.rutaArchivoAFD);

            // El bucle que llama a yylex() hasta el fin de la cadena
            while (true) {
                int token = analizador.yylex();

                // Si el token es FIN, terminamos el bucle
                if (token == SimbEsp.FIN()) {
                    tableModel.addRow(new Object[]{SimbEsp.FIN(), " "});
                    break;
                }

                String lexema = analizador.lexema;

                // Añadimos una nueva fila a la tabla con el resultado
                tableModel.addRow(new Object[]{token, lexema});
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error durante el análisis: " + e.getMessage(), "Error de Análisis", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAnalizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnCargarArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane scrollPaneTabla;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtRutaArchivo;
    private javax.swing.JTextField txtSigma;
    // End of variables declaration//GEN-END:variables
}
