/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication20;

/**
 *
 * @author osman
 */
public class PanelLR0 extends javax.swing.JPanel {

    private javax.swing.table.DefaultTableModel tableModel;
    
    private String rutaArchivoAFD;
    private String rutaArchivoAFD2;
    // En tu clase PanelLR0
    private AnalizadorLR0 analLR0;

    // para recordar la ruta de los AFD (si usas 2 diferentes)
    private String rutaAFDLexico;
    private String rutaAFDGramGram;
    /**
     * Creates new form PanelLR0
     */
    public PanelLR0() {
        initComponents();
        
        tableModel = (javax.swing.table.DefaultTableModel) tblLexico.getModel();
    }
    
    private void llenarTablaNoTerminales() {
        if (analLR0 == null) return;

        javax.swing.table.DefaultTableModel model =
                new javax.swing.table.DefaultTableModel(
                        new Object[]{"No terminal"}, 0);

        for (String nt : analLR0.vn) {
            model.addRow(new Object[]{ nt });
        }

        tablaNoTerminales.setModel(model);
    }

    private void llenarTablaTerminales() {
        if (analLR0 == null) return;

        javax.swing.table.DefaultTableModel model =
                new javax.swing.table.DefaultTableModel(
                        new Object[]{"Terminal", "Token"}, 0);

        for (String t : analLR0.vt2) {
            model.addRow(new Object[]{ t, "" }); // token lo llenas a mano y luego botón
        }

        tablaTerminales.setModel(model);
    }
    
    private void llenarTablaLR0() {
        if (analLR0 == null) return;

        // Construimos encabezados
        int numTerm = analLR0.vt2.length + 1;   // + "$"
        int numNoTerm = analLR0.vn.length;

        String[] columnas = new String[1 + numTerm + numNoTerm];
        columnas[0] = "Edo";

        int idx = 1;
        for (String t : analLR0.vt2) {
            columnas[idx++] = t;
        }
        columnas[idx++] = "$";           // último terminal
        for (String nt : analLR0.vn) {
            columnas[idx++] = nt;
        }

        javax.swing.table.DefaultTableModel model =
                new javax.swing.table.DefaultTableModel(columnas, 0);

        // Rellenar filas
        for (int i = 0; i < analLR0.numEstados; i++) {
            Object[] fila = new Object[columnas.length];
            fila[0] = i; // número de estado

            int col = 1;

            // ACTION (terminales)
            for (int j = 0; j < numTerm; j++) {
                fila[col++] = analLR0.actionLR0[i][j];
            }

            // GOTO (no terminales)
            for (int j = 0; j < numNoTerm; j++) {
                int destino = analLR0.gotoLR0[i][j];
                fila[col++] = (destino >= 0) ? destino : "";
            }

            model.addRow(fila);
        }

        tablaLR0.setModel(model);
    }
    
    private void llenarTablaIrA() {
        if (analLR0 == null) return;

        javax.swing.table.DefaultTableModel model =
                new javax.swing.table.DefaultTableModel(
                        new Object[]{"Edo", "IrA(Edo, Símbolo)", "Items destino"}, 0);

        for (int k = 0; k < analLR0.numRenglonesIrA; k++) {
            Inf_IrA info = analLR0.resultIrA[k];
            if (info == null) continue;

            // la fila inicial tiene irA_Sj = -1 (solo describe S0), también la mostramos
            String edoOrigen  = (info.irA_Sj >= 0) ? String.valueOf(info.irA_Sj) : "";
            String irAString;

            if (info.irA_Sj >= 0) {
                irAString = "IrA(" + info.irA_Sj + ", " + info.irA_Simbolo + ") = " + info.Si;
            } else {
                irAString = "S0";
            }

            String items = info.ConjuntoItems; // ya lo llenas en CrearTablaLR0

            model.addRow(new Object[]{ edoOrigen, irAString, items });
        }

        tablaIrA.setModel(model);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtGramatica = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtRutaArchivo = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSigma = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAnalisis = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaTerminales = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaIrA = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblLexico = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        txtRutaArchivo2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaNoTerminales = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaLR0 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Análisis LR(0)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(542, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(505, 505, 505))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 90));

        txtGramatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGramaticaActionPerformed(evt);
            }
        });
        add(txtGramatica, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 101, 401, 169));

        jButton2.setBackground(new java.awt.Color(102, 0, 204));
        jButton2.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Asignar tokens a terminales");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 276, 205, -1));

        txtRutaArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaArchivoActionPerformed(evt);
            }
        });
        add(txtRutaArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 101, 245, -1));

        jButton3.setBackground(new java.awt.Color(102, 0, 204));
        jButton3.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Seleccionar AFD léxico");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 102, -1, -1));

        jLabel3.setText("Sigma:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 207, -1, -1));
        add(txtSigma, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 207, 396, 63));

        jButton4.setBackground(new java.awt.Color(102, 0, 204));
        jButton4.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Analizar sintácticamente sigma");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 276, -1, -1));

        tablaAnalisis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Pila", "Cadena", "Acción"
            }
        ));
        jScrollPane2.setViewportView(tablaAnalisis);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 304, 659, 130));

        tablaTerminales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Terminal", "Token"
            }
        ));
        jScrollPane4.setViewportView(tablaTerminales);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 304, 205, 130));

        tablaIrA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Edo", "IrA(Edo,Simbolo)", "Items"
            }
        ));
        jScrollPane5.setViewportView(tablaIrA);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 401, 150));

        tblLexico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Lexema", "Token"
            }
        ));
        jScrollPane6.setViewportView(tblLexico);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(999, 101, 186, 169));

        jButton5.setBackground(new java.awt.Color(102, 0, 204));
        jButton5.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Probar léxico");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1076, 276, -1, -1));
        add(txtRutaArchivo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 152, 245, -1));

        jButton6.setBackground(new java.awt.Color(102, 0, 204));
        jButton6.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Seleccionar AFD GramGram");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 153, -1, -1));

        tablaNoTerminales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "No terminal"
            }
        ));
        jScrollPane3.setViewportView(tablaNoTerminales);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 304, 109, 130));

        jButton1.setBackground(new java.awt.Color(102, 0, 204));
        jButton1.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Crear tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 276, 109, -1));

        jLabel4.setText("Tabla IrA()");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, -1, -1));

        jLabel5.setText("Tabla LR(0)");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        tablaLR0.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tablaLR0);

        add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 401, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void txtGramaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGramaticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGramaticaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                                
        if (analLR0 == null) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Primero crea la tabla LR(0).",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        javax.swing.table.TableModel model = tablaTerminales.getModel();
        int filas = model.getRowCount();

        for (int i = 0; i < filas; i++) {
            Object simbObj  = model.getValueAt(i, 0); // columna Terminal
            Object tokenObj = model.getValueAt(i, 1); // columna Token

            if (simbObj == null) continue;
            String simb = simbObj.toString().trim();
            if (simb.isEmpty()) continue;

            int token = -1;
            if (tokenObj != null && !tokenObj.toString().trim().isEmpty()) {
                try {
                    token = Integer.parseInt(tokenObj.toString().trim());
                } catch (NumberFormatException e) {
                    // si no es número, lo ignoramos o mostramos aviso
                    javax.swing.JOptionPane.showMessageDialog(
                            this,
                            "Token inválido en la fila " + i + " para el terminal '" + simb + "'.",
                            "Advertencia",
                            javax.swing.JOptionPane.WARNING_MESSAGE);
                    continue;
                }
            }

            // Buscar el índice del terminal en el arreglo vt2 de AnalizadorLR0
            for (int j = 0; j < analLR0.vt2.length; j++) {
                if (analLR0.vt2[j].equals(simb)) {
                    analLR0.vt3[j] = token;      // guardamos token numérico
                    analLR0.vt[j].token = token; // opcional: también en el SimbolG
                    break;
                }
            }
        }

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Tokens asignados a los terminales.",
                "Listo",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtRutaArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaArchivoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Seleccionar archivo de AFD (.txt)");

        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = fileChooser.getSelectedFile();
            this.rutaArchivoAFD = archivo.getAbsolutePath(); // Guardamos la ruta en la variable de instancia
            txtRutaArchivo.setText(this.rutaArchivoAFD); // Mostramos la ruta en el TextField
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                                                        
        if (analLR0 == null) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Primero crea la tabla LR(0).",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String sigma = txtSigma.getText().trim();
        if (sigma.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Escribe una cadena sigma para analizar.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            java.util.List<String[]> pasos = analLR0.analizarCadenaLR0(sigma);

            javax.swing.table.DefaultTableModel model =
                    new javax.swing.table.DefaultTableModel(
                            new Object[]{"Pila", "Cadena", "Acción"}, 0);

            for (String[] fila : pasos) {
                model.addRow(fila);
            }

            tablaAnalisis.setModel(model);

        } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error durante el análisis LR(0):\n" + ex.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // --- 1. Obtener las entradas del usuario y validar ---
        String cadena = txtSigma.getText();

        if (cadena.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingresa una cadena para analizar.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (this.rutaArchivoAFD == null || this.rutaArchivoAFD.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, carga un archivo de definición de AFD.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // --- 2. Limpiar la tabla de resultados anteriores ---
        tableModel.setRowCount(0);

        // --- 3. Crear el analizador y procesar la cadena ---
        try {
            analizadorLexico analizador = new analizadorLexico(cadena, this.rutaArchivoAFD);

            // El bucle que llama a yylex() hasta el fin de la cadena
            while (true) {
                int token = analizador.yylex();

                // Si el token es FIN, terminamos el bucle
                if (token == SimbEsp.FIN()) {
                    tableModel.addRow(new Object[]{SimbEsp.FIN(), " "});
                    break;
                }

                String lexema = analizador.lexema;

                // Añadimos una nueva fila a la tabla con el resultado
                tableModel.addRow(new Object[]{token, lexema});
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error durante el análisis: " + e.getMessage(), "Error de Análisis", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Seleccionar archivo de AFD (.txt)");

        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = fileChooser.getSelectedFile();
            this.rutaArchivoAFD2 = archivo.getAbsolutePath(); // Guardamos la ruta en la variable de instancia
            txtRutaArchivo2.setText(this.rutaArchivoAFD2); // Mostramos la ruta en el TextField
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String gr = txtGramatica.getText().trim();
    if (gr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Escribe una gramática primero.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Verificamos que ya seleccionaste el AFD de GramGram (rutaArchivoAFD2)
    if (this.rutaArchivoAFD2 == null || this.rutaArchivoAFD2.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Por favor, selecciona el AFD de GramGram.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // 1) Crear analizador LR(0) con la gramática y el AFD de GramGram
        analLR0 = new AnalizadorLR0(gr, this.rutaArchivoAFD2);

        // 2) Construir autómata LR(0) (conjuntos Si e IrA)
        analLR0.CrearTablaLR0();

        // 3) Construir tablas ACTION/GOTO
        analLR0.construirTablasLR0();

        // 4) Llenar tablas del panel
        llenarTablaNoTerminales();
        llenarTablaTerminales();
        llenarTablaLR0();
        llenarTablaIrA();

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Autómata y tabla LR(0) construidos correctamente.",
                "Listo",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception ex) {
        ex.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ocurrió un error al construir la tabla LR(0):\n" + ex.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tablaAnalisis;
    private javax.swing.JTable tablaIrA;
    private javax.swing.JTable tablaLR0;
    private javax.swing.JTable tablaNoTerminales;
    private javax.swing.JTable tablaTerminales;
    private javax.swing.JTable tblLexico;
    private javax.swing.JTextField txtGramatica;
    private javax.swing.JTextField txtRutaArchivo;
    private javax.swing.JTextField txtRutaArchivo2;
    private javax.swing.JTextField txtSigma;
    // End of variables declaration//GEN-END:variables
}
