package javaapplication20;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author osman y sof
 */
public class PanelCalc extends javax.swing.JPanel {
    /**
     * Creates new form PanelCalc
     */
    private Calculadora calc; 
    private String archivoAFD; 
    
    
    public PanelCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAFD = new javax.swing.JTextField();
        txtExpresion = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        txtPostfijo = new javax.swing.JTextField();
        btnCargar = new javax.swing.JButton();
        btnEvaluar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CALCULADORA CIENTÍFICA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 100));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Analizador Léxico");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Expresión a evaluar");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Resultado");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, 20));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("Postfijo");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        txtAFD.setName("txtAFD"); // NOI18N
        txtAFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAFDActionPerformed(evt);
            }
        });
        add(txtAFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 270, -1));
        add(txtExpresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 270, -1));

        txtResultado.setEditable(false);
        txtResultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 270, -1));

        txtPostfijo.setEditable(false);
        txtPostfijo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(txtPostfijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 270, -1));

        btnCargar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        btnEvaluar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEvaluar.setText("Evaluar");
        btnEvaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarActionPerformed(evt);
            }
        });
        add(btnEvaluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));
    }// </editor-fold>                        

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) { //file chooser                                         
        JFileChooser fc = new JFileChooser();
            fc.setDialogTitle("Seleccionar archivo del AFD");
            int seleccion = fc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                archivoAFD = file.getAbsolutePath();
                txtAFD.setText(archivoAFD);
                try {
                    calc = new Calculadora("", archivoAFD);
                    JOptionPane.showMessageDialog(this, "AFD cargado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error al cargar el AFD:\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
    }                                         

    private void txtAFDActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void btnEvaluarActionPerformed(java.awt.event.ActionEvent evt) {     ///evaluar expresion con calculadora                                      
        if (calc == null) {
                JOptionPane.showMessageDialog(this, "Primero carga un archivo AFD.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

        String expresion = txtExpresion.getText().trim(); //quitamos los espacios para que no marque error
        if (expresion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa una expresión a evaluar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        calc.setExpresion(expresion); //Le damos a calculadora la expresion sigma para que la analice

        if (calc.iniEval()) { // Le pasamos el resultado y la expresion en postfijo a los JtextField
            txtResultado.setText(String.valueOf(calc.result));
            txtPostfijo.setText(calc.ExprPost);
        } else { //Sino se puede realizar la operacion por error de sintaxis, ya que el analizador no lo reconoce
            txtResultado.setText("Error de sintaxis");
            txtPostfijo.setText("");
        }
    }                                          


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnEvaluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAFD;
    private javax.swing.JTextField txtExpresion;
    private javax.swing.JTextField txtPostfijo;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration                   
}
