/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication20;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author osman
 */
public class PanelOpc extends javax.swing.JPanel {

    /**
     * Creates new form PanelOpc
     */
    public PanelOpc() {
        initComponents();
    }

    
    public void inicializarComboBoxes() {
        DefaultComboBoxModel<String> modelo1 = new DefaultComboBoxModel<>();

        // Obtenemos todos los IDs disponibles
        for (Integer id : AFN.afnC.keySet()) {
            String idStr = id.toString();
            modelo1.addElement(idStr);
        }

        // Asignamos un modelo a cada ComboBox
        jCB1.setModel(modelo1);
    }

    public void actualizarComboBox() {
        // Creamos un nuevo modelo de datos para el ComboBox
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        
        // Accedemos DIRECTAMENTE al mapa estático de la clase AFN
        // (Suponiendo que tu mapa se llama 'afnC' y es public static)
        for (Integer id : AFN.afnC.keySet()) {
            modelo.addElement(id.toString());
        }
        
        // Asignamos el modelo lleno de IDs al ComboBox de este panel
        jCB1.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jCB1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Aplicar operación ? a:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jCB1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jCB1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(jCB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 100, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Realizar operación ?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("OPCIONAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/opc.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 280, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // --- 1. Obtener las selecciones de los ComboBox ---
            Object seleccionado1 = jCB1.getSelectedItem();

            // --- 2. Validar las entradas ---
            if (seleccionado1 == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona dos AFN para unir.");
                return;
            }

            int id1 = Integer.parseInt(seleccionado1.toString());

            // --- 3. Recuperar los AFNs del Mapa ---
            AFN afn1 = AFN.afnC.get(id1);

            // --- 4. Realizar la operacion ---
            afn1.Opcional();

            // El afn1 ya está actualizado en el mapa, no hay que volver a ponerlo.

            javax.swing.JOptionPane.showMessageDialog(this, "Operacion ? exitosa, aplicada al AFN "+id1);

            // --- 6. Actualizar los ComboBoxes ---
            // Es crucial actualizar la vista para que refleje la eliminación del id2.
            this.inicializarComboBoxes();

        } catch (Exception e) {
            // Capturamos cualquier error inesperado
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCB1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
