/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication20;

/**
 *
 * @author osman
 */
public class PanelBasico extends javax.swing.JPanel {

    /**
     * Creates new form PanelBasico
     */
    public PanelBasico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCB = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jInf = new javax.swing.JTextField();
        jSup = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jID = new javax.swing.JTextField();
        jCrear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(240, 240, 240));
        setPreferredSize(new java.awt.Dimension(600, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCB.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jCB.setText("Usar código ASCII");
        jCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBActionPerformed(evt);
            }
        });
        add(jCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("Caracter inferior");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Caracter superior");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));
        add(jInf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 110, -1));
        add(jSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 109, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("ID del AFN");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIDActionPerformed(evt);
            }
        });
        add(jID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 109, -1));

        jCrear.setBackground(new java.awt.Color(51, 78, 235));
        jCrear.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jCrear.setForeground(new java.awt.Color(255, 255, 255));
        jCrear.setText("Crear AFN");
        jCrear.setBorderPainted(false);
        jCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearActionPerformed(evt);
            }
        });
        add(jCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 120, -1));

        jPanel1.setBackground(new java.awt.Color(51, 78, 235));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CREAR BÁSICO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel4)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/basico.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 250, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void jIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIDActionPerformed

    private void jCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearActionPerformed
       try {
            // 1. OBTENER DATOS DE LA INTERFAZ
            String infStr = jInf.getText();
            String supStr = jSup.getText();
            String idStr = jID.getText();

            // 2. VALIDAR CAMPOS VACÍOS
            if (infStr.isEmpty() || supStr.isEmpty() || idStr.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
                return;
            }

            // Convertimos el ID a entero
            int idI = Integer.parseInt(idStr);

            // Validamos que el ID no exista ya en el mapa
            if (AFN.afnC.containsKey(idI)) {
                javax.swing.JOptionPane.showMessageDialog(this, "El ID " + idI + " ya existe. Por favor, elige otro.");
                return;
            }

            AFN afn = new AFN();

            // 3. DECIDIR EL MODO (ASCII o Carácter)
            if (jCB.isSelected()) { // MODO ASCII
                int infI = Integer.parseInt(infStr);
                int supI = Integer.parseInt(supStr);

                // 4. VALIDACIÓN LÓGICA: inferior <= superior
                if (infI > supI) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error: El valor inferior no puede ser mayor que el superior.");
                    return;
                }

                // 5. LLAMADA CORRECTA A LOS MÉTODOS
                afn.CrearBasico(infI, supI); // Orden (inf, sup) y se pasa el ID

            } else { // MODO CARÁCTER
                char infC = infStr.charAt(0);
                char supC = supStr.charAt(0);

                // 4. VALIDACIÓN LÓGICA: inferior <= superior
                if (infC > supC) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error: El carácter inferior no puede ser mayor que el superior.");
                    return;
                }

                // 5. LLAMADA CORRECTA A LOS MÉTODOS
                afn.CrearBasico(infC, supC); // Orden (inf, sup) y se pasa el ID
            }

            // 6. LÓGICA DE GUARDADO CORRECTA
            // Guardamos el AFN recién creado en el mapa estático de la clase AFN.
            AFN.afnC.put(idI, afn);

            javax.swing.JOptionPane.showMessageDialog(this, "AFN con ID " + idI + " creado y guardado exitosamente.");

            // Limpiamos los campos para la siguiente entrada
            jInf.setText("");
            jSup.setText("");
            jID.setText("");

        } catch (NumberFormatException e) {
            // Manejamos el error si el usuario no escribe un número
            javax.swing.JOptionPane.showMessageDialog(this, "Error: El ID y los límites (si se usan) deben ser números válidos.");
        }
    }//GEN-LAST:event_jCrearActionPerformed

    private void jCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCB;
    private javax.swing.JButton jCrear;
    private javax.swing.JTextField jID;
    private javax.swing.JTextField jInf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jSup;
    // End of variables declaration//GEN-END:variables
}
